/* confdefs.h */
#define PACKAGE_NAME ""
#define PACKAGE_TARNAME ""
#define PACKAGE_VERSION ""
#define PACKAGE_STRING ""
#define PACKAGE_BUGREPORT ""
#define PACKAGE_URL ""
#define HAVE_LIBXPM 1
#define USE_LIBXPM 1
#define HAVE_FT2 1
#define HAVE_FONTCONFIG 1
#define USE_FONTCONFIG 1
#define HAVE_XFT 1
#define USE_XFT 1
#define HAVE_LIBPNG 1
#define USE_LIBPNG 1
#define HAVE_ZLIB 1
#define USE_ZLIB 1
#define HAVE_LIBICONV 1
#define USE_LIBICONV 1
#define HAVE_PCRE 1
#define HAVE_LIBPAPER 1
#define USE_LIBPAPER 1
#define HAVE_LIBJPEG 1
#define USE_LIBJPEG 1
#define HAVE_LIBTIFF 1
#define USE_LIBTIFF 1
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_FCNTL_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_UNISTD_H 1
#define HAVE_GTK 1
#define USE_GTK 1
#define HAVE_MOTIF 1
#define USE_MOTIF 1
#define HAVE_ENCHANT 1
#define USE_ENCHANT 1
#define HAVE_SOCKET 1
#define HAVE_STRERROR 1
#define HAVE_UNAME 1
#define PREFIX "/usr"
#define EXEC_PREFIX "/usr"
#define BINDIR "/usr/bin"
#define DATADIR "/usr/share"
#define Q_PREFIX /usr
#define Q_EXEC_PREFIX /usr
#define Q_BINDIR /usr/bin
#define Q_DATADIR /usr/share
#define USE_GTK 1 
#define USE_MOTIF 0 
#define USE_HEADLESS 0 
