/************************************************************************/
/*									*/
/*  Microsoft language tags.						*/
/*									*/
/************************************************************************/

#   include	"textMsLcid.h"

const MsLcid TEXT_LcIds[]=
{
    { 0x0036, "af", "Afrikaans", "Afrikaans", },
    { 0x0436, "af_ZA", "Afrikaans (South Africa)", "Afrikaans (Suid Afrika)", },
    { 0x001C, "sq", "Albanian", "shqipe", },
    { 0x041C, "sq_AL", "Albanian (Albania)", "shqipe (Shqipëria)", },
    { 0x0484, "gsw_FR", "Alsatian (France)", "Elsässisch (Frànkrisch)", },
    { 0x045E, "am_ET", "Amharic (Ethiopia)", "አማርኛ (ኢትዮጵያ)", },
    { 0x0001, "ar", "Arabic", "العربية", },
    { 0x1401, "ar_DZ", "Arabic (Algeria)", "العربية (الجزائر)", },
    { 0x3C01, "ar_BH", "Arabic (Bahrain)", "العربية (البحرين)", },
    { 0x0C01, "ar_EG", "Arabic (Egypt)", "العربية (مصر)", },
    { 0x0801, "ar_IQ", "Arabic (Iraq)", "العربية (العراق)", },
    { 0x2C01, "ar_JO", "Arabic (Jordan)", "العربية (الأردن)", },
    { 0x3401, "ar_KW", "Arabic (Kuwait)", "العربية (الكويت)", },
    { 0x3001, "ar_LB", "Arabic (Lebanon)", "العربية (لبنان)", },
    { 0x1001, "ar_LY", "Arabic (Libya)", "العربية (ليبيا)", },
    { 0x1801, "ar_MA", "Arabic (Morocco)", "العربية (المملكة المغربية)", },
    { 0x2001, "ar_OM", "Arabic (Oman)", "العربية (عمان)", },
    { 0x4001, "ar_QA", "Arabic (Qatar)", "العربية (قطر)", },
    { 0x0401, "ar_SA", "Arabic (Saudi Arabia)", "العربية (المملكة العربية السعودية)", },
    { 0x2801, "ar_SY", "Arabic (Syria)", "العربية (سوريا)", },
    { 0x1C01, "ar_TN", "Arabic (Tunisia)", "العربية (تونس)", },
    { 0x3801, "ar_AE", "Arabic (U.A.E.)", "العربية (الإمارات العربية المتحدة)", },
    { 0x2401, "ar_YE", "Arabic (Yemen)", "العربية (اليمن)", },
    { 0x002B, "hy", "Armenian", "Հայերեն", },
    { 0x042B, "hy_AM", "Armenian (Armenia)", "Հայերեն (Հայաստան)", },
    { 0x044D, "as_IN", "Assamese (India)", "অসমীয়া (ভাৰত)", },
    { 0x002C, "az", "Azeri", "Azərbaycan­ılı", },
    { 0x082C, "az_Cyrl_AZ", "Azeri (Cyrillic, Azerbaijan)", "Азәрбајҹан (Азәрбајҹан)", },
    { 0x042C, "az_Latn_AZ", "Azeri (Latin, Azerbaijan)", "Azərbaycan­ılı (Azərbaycanca)", },
    { 0x046D, "ba_RU", "Bashkir (Russia)", "Башҡорт (Россия)", },
    { 0x002D, "eu", "Basque", "euskara", },
    { 0x042D, "eu_ES", "Basque (Basque)", "euskara (euskara)", },
    { 0x0023, "be", "Belarusian", "Беларускі", },
    { 0x0423, "be_BY", "Belarusian (Belarus)", "Беларускі (Беларусь)", },
    { 0x0845, "bn_BD", "Bengali (Bangladesh)", "বাংলা (বাংলা)", },
    { 0x0445, "bn_IN", "Bengali (India)", "বাংলা (ভারত)", },
    { 0x201A, "bs_Cyrl_BA", "Bosnian (Cyrillic, Bosnia and Herzegovina)", "босански (Босна и Херцеговина)", },
    { 0x141A, "bs_Latn_BA", "Bosnian (Latin, Bosnia and Herzegovina)", "bosanski (Bosna i Hercegovina)", },
    { 0x047E, "br_FR", "Breton (France)", "brezhoneg (Frañs)", },
    { 0x0002, "bg", "Bulgarian", "български", },
    { 0x0402, "bg_BG", "Bulgarian (Bulgaria)", "български (България)", },
    { 0x0003, "ca", "Catalan", "català", },
    { 0x0403, "ca_ES", "Catalan (Catalan)", "català (català)", },
    { 0x0C04, "zh_HK", "Chinese (Hong Kong S.A.R.)", "中文(香港特别行政區)", },
    { 0x1404, "zh_MO", "Chinese (Macao S.A.R.)", "中文(澳門特别行政區)", },
    { 0x0804, "zh_CN", "Chinese (People's Republic of China)", "中文(中华人民共和国)", },
    { 0x0004, "zh_Hans", "Chinese (Simplified)", "中文(简体)", },
    { 0x1004, "zh_SG", "Chinese (Singapore)", "中文(新加坡)", },
    { 0x0404, "zh_TW", "Chinese (Taiwan)", "中文(台灣)", },
    { 0x7C04, "zh_Hant", "Chinese (Traditional)", "中文(繁體)", },
    { 0x0483, "co_FR", "Corsican (France)", "Corsu (France)", },
    { 0x001A, "hr", "Croatian", "hrvatski", },
    { 0x041A, "hr_HR", "Croatian (Croatia)", "hrvatski (Hrvatska)", },
    { 0x101A, "hr_BA", "Croatian (Latin, Bosnia and Herzegovina)", "hrvatski (Bosna i Hercegovina)", },
    { 0x0005, "cs", "Czech", "čeština", },
    { 0x0405, "cs_CZ", "Czech (Czech Republic)", "čeština (Česká republika)", },
    { 0x0006, "da", "Danish", "dansk", },
    { 0x0406, "da_DK", "Danish (Denmark)", "dansk (Danmark)", },
    { 0x048C, "prs_AF", "Dari (Afghanistan)", "درى (افغانستان)", },
    { 0x0065, "div", "Divehi", "ދިވެހިބަސް", },
    { 0x0465, "div_MV", "Divehi (Maldives)", "ދިވެހިބަސް (ދިވެހި ރާއްޖެ)", },
    { 0x0013, "nl", "Dutch", "Nederlands", },
    { 0x0813, "nl_BE", "Dutch (Belgium)", "Nederlands (België)", },
    { 0x0413, "nl_NL", "Dutch (Netherlands)", "Nederlands (Nederland)", },
    { 0x0009, "en", "English", "English", },
    { 0x0C09, "en_AU", "English (Australia)", "English (Australia)", },
    { 0x2809, "en_BZ", "English (Belize)", "English (Belize)", },
    { 0x1009, "en_CA", "English (Canada)", "English (Canada)", },
    { 0x2409, "en_029", "English (Caribbean)", "English (Caribbean)", },
    { 0x4009, "en_IN", "English (India)", "English (India)", },
    { 0x1809, "en_IE", "English (Ireland)", "English (Eire)", },
    { 0x2009, "en_JM", "English (Jamaica)", "English (Jamaica)", },
    { 0x4409, "en_MY", "English (Malaysia)", "English (Malaysia)", },
    { 0x1409, "en_NZ", "English (New Zealand)", "English (New Zealand)", },
    { 0x3409, "en_PH", "English (Republic of the Philippines)", "English (Philippines)", },
    { 0x4809, "en_SG", "English (Singapore)", "English (Singapore)", },
    { 0x1C09, "en_ZA", "English (South Africa)", "English (South Africa)", },
    { 0x2C09, "en_TT", "English (Trinidad and Tobago)", "English (Trinidad y Tobago)", },
    { 0x0809, "en_GB", "English (United Kingdom)", "English (United Kingdom)", },
    { 0x0409, "en_US", "English (United States)", "English (United States)", },
    { 0x3009, "en_ZW", "English (Zimbabwe)", "English (Zimbabwe)", },
    { 0x0025, "et", "Estonian", "eesti", },
    { 0x0425, "et_EE", "Estonian (Estonia)", "eesti (Eesti)", },
    { 0x0038, "fo", "Faroese", "føroyskt", },
    { 0x0438, "fo_FO", "Faroese (Faroe Islands)", "føroyskt (Føroyar)", },
    { 0x0464, "fil_PH", "Filipino (Philippines)", "Filipino (Pilipinas)", },
    { 0x000B, "fi", "Finnish", "suomi", },
    { 0x040B, "fi_FI", "Finnish (Finland)", "suomi (Suomi)", },
    { 0x000C, "fr", "French", "français", },
    { 0x080C, "fr_BE", "French (Belgium)", "français (Belgique)", },
    { 0x0C0C, "fr_CA", "French (Canada)", "français (Canada)", },
    { 0x040C, "fr_FR", "French (France)", "français (France)", },
    { 0x140C, "fr_LU", "French (Luxembourg)", "français (Luxembourg)", },
    { 0x180C, "fr_MC", "French (Principality of Monaco)", "français (Principauté de Monaco)", },
    { 0x100C, "fr_CH", "French (Switzerland)", "français (Suisse)", },
    { 0x0462, "fy_NL", "Frisian (Netherlands)", "Frysk (Nederlân)", },
    { 0x0056, "gl", "Galician", "galego", },
    { 0x0456, "gl_ES", "Galician (Galician)", "galego (galego)", },
    { 0x0037, "ka", "Georgian", "ქართული", },
    { 0x0437, "ka_GE", "Georgian (Georgia)", "ქართული (საქართველო)", },
    { 0x0007, "de", "German", "Deutsch", },
    { 0x0C07, "de_AT", "German (Austria)", "Deutsch (Österreich)", },
    { 0x0407, "de_DE", "German (Germany)", "Deutsch (Deutschland)", },
    { 0x1407, "de_LI", "German (Liechtenstein)", "Deutsch (Liechtenstein)", },
    { 0x1007, "de_LU", "German (Luxembourg)", "Deutsch (Luxemburg)", },
    { 0x0807, "de_CH", "German (Switzerland)", "Deutsch (Schweiz)", },
    { 0x0008, "el", "Greek", "ελληνικά", },
    { 0x0408, "el_GR", "Greek (Greece)", "ελληνικά (Ελλάδα)", },
    { 0x046F, "kl_GL", "Greenlandic (Greenland)", "kalaallisut (Kalaallit Nunaat)", },
    { 0x0047, "gu", "Gujarati", "ગુજરાતી", },
    { 0x0447, "gu_IN", "Gujarati (India)", "ગુજરાતી (ભારત)", },
    { 0x0468, "ha_Latn_NG", "Hausa (Latin, Nigeria)", "Hausa (Nigeria)", },
    { 0x000D, "he", "Hebrew", "עברית", },
    { 0x040D, "he_IL", "Hebrew (Israel)", "עברית (ישראל)", },
    { 0x0039, "hi", "Hindi", "हिंदी", },
    { 0x0439, "hi_IN", "Hindi (India)", "हिंदी (भारत)", },
    { 0x000E, "hu", "Hungarian", "magyar", },
    { 0x040E, "hu_HU", "Hungarian (Hungary)", "magyar (Magyarország)", },
    { 0x000F, "is", "Icelandic", "íslenska", },
    { 0x040F, "is_IS", "Icelandic (Iceland)", "íslenska (Ísland)", },
    { 0x0470, "ig_NG", "Igbo (Nigeria)", "Igbo (Nigeria)", },
    { 0x0021, "id", "Indonesian", "Bahasa Indonesia", },
    { 0x0421, "id_ID", "Indonesian (Indonesia)", "Bahasa Indonesia (Indonesia)", },
    { 0x085D, "iu_Latn_CA", "Inuktitut (Latin, Canada)", "Inuktitut (Kanatami) (kanata)", },
    { 0x045D, "iu_Cans_CA", "Inuktitut (Syllabics, Canada)", "ᐃᓄᒃᑎᑐᑦ (ᑲᓇᑕ)", },
    { 0x083C, "ga_IE", "Irish (Ireland)", "Gaeilge (Éire)", },
    { 0x0434, "xh_ZA", "isiXhosa (South Africa)", "isiXhosa (uMzantsi Afrika)", },
    { 0x0435, "zu_ZA", "isiZulu (South Africa)", "isiZulu (iNingizimu Afrika)", },
    { 0x0010, "it", "Italian", "italiano", },
    { 0x0410, "it_IT", "Italian (Italy)", "italiano (Italia)", },
    { 0x0810, "it_CH", "Italian (Switzerland)", "italiano (Svizzera)", },
    { 0x0011, "ja", "Japanese", "日本語", },
    { 0x0411, "ja_JP", "Japanese (Japan)", "日本語 (日本)", },
    { 0x004B, "kn", "Kannada", "ಕನ್ನಡ", },
    { 0x044B, "kn_IN", "Kannada (India)", "ಕನ್ನಡ (ಭಾರತ)", },
    { 0x003F, "kk", "Kazakh", "Қазащb", },
    { 0x043F, "kk_KZ", "Kazakh (Kazakhstan)", "Қазақ (Қазақстан)", },
    { 0x0453, "km_KH", "Khmer (Cambodia)", "ខ្មែរ (កម្ពុជា)", },
    { 0x0486, "qut_GT", "K'iche (Guatemala)", "K'iche (Guatemala)", },
    { 0x0487, "rw_RW", "Kinyarwanda (Rwanda)", "Kinyarwanda (Rwanda)", },
    { 0x0041, "sw", "Kiswahili", "Kiswahili", },
    { 0x0441, "sw_KE", "Kiswahili (Kenya)", "Kiswahili (Kenya)", },
    { 0x0057, "kok", "Konkani", "कोंकणी", },
    { 0x0457, "kok_IN", "Konkani (India)", "कोंकणी (भारत)", },
    { 0x0012, "ko", "Korean", "한국어", },
    { 0x0412, "ko_KR", "Korean (Korea)", "한국어 (대한민국)", },
    { 0x0040, "ky", "Kyrgyz", "Кыргыз", },
    { 0x0440, "ky_KG", "Kyrgyz (Kyrgyzstan)", "Кыргыз (Кыргызстан)", },
    { 0x0454, "lo_LA", "Lao (Lao P.D.R.)", "ລາວ (ສ.ປ.ປ. ລາວ)", },
    { 0x0026, "lv", "Latvian", "latviešu", },
    { 0x0426, "lv_LV", "Latvian (Latvia)", "latviešu (Latvija)", },
    { 0x0027, "lt", "Lithuanian", "lietuvių", },
    { 0x0427, "lt_LT", "Lithuanian (Lithuania)", "lietuvių (Lietuva)", },
    { 0x082E, "wee_DE", "Lower Sorbian (Germany)", "dolnoserbšćina (Nimska)", },
    { 0x046E, "lb_LU", "Luxembourgish (Luxembourg)", "Lëtzebuergesch (Luxembourg)", },
    { 0x002F, "mk", "Macedonian", "македонски јазик", },
    { 0x042F, "mk_MK", "Macedonian (Former Yugoslav Republic of Macedonia)", "македонски јазик (Македонија)", },
    { 0x003E, "ms", "Malay", "Bahasa Malaysia", },
    { 0x083E, "ms_BN", "Malay (Brunei Darussalam)", "Bahasa Malaysia (Brunei Darussalam)", },
    { 0x043E, "ms_MY", "Malay (Malaysia)", "Bahasa Malaysia (Malaysia)", },
    { 0x044C, "ml_IN", "Malayalam (India)", "മലയാളം (ഭാരതം)", },
    { 0x043A, "mt_MT", "Maltese (Malta)", "Malti (Malta)", },
    { 0x0481, "mi_NZ", "Maori (New Zealand)", "Reo Māori (Aotearoa)", },
    { 0x047A, "arn_CL", "Mapudungun (Chile)", "Mapudungun (Chile)", },
    { 0x004E, "mr", "Marathi", "मराठी", },
    { 0x044E, "mr_IN", "Marathi (India)", "मराठी (भारत)", },
    { 0x047C, "moh_CA", "Mohawk (Mohawk)", "Kanien'kéha (Canada)", },
    { 0x0050, "mn", "Mongolian", "Монгол хэл", },
    { 0x0450, "mn_MN", "Mongolian (Cyrillic, Mongolia)", "Монгол хэл (Монгол улс)", },
    { 0x0850, "mn_Mong_CN", "Mongolian (Traditional Mongolian, PRC)", "ᠮᠣᠩᠭᠤᠯ ᠬᠡᠯᠡ (ᠪᠦᠭᠦᠳᠡ ᠨᠠᠢᠷᠠᠮᠳᠠᠬᠤ ᠳᠤᠮᠳᠠᠳᠤ ᠠᠷᠠᠳ ᠣᠯᠣᠰ)", },
    { 0x0461, "ne_NP", "Nepali (Nepal)", "नेपाली (नेपाल)", },
    { 0x0014, "no", "Norwegian", "norsk", },
    { 0x0414, "nb_NO", "Norwegian, Bokmål (Norway)", "norsk, bokmål (Norge)", },
    { 0x0814, "nn_NO", "Norwegian, Nynorsk (Norway)", "norsk, nynorsk (Noreg)", },
    { 0x0482, "oc_FR", "Occitan (France)", "Occitan (França)", },
    { 0x0448, "or_IN", "Oriya (India)", "ଓଡ଼ିଆ (ଭାରତ)", },
    { 0x0463, "ps_AF", "Pashto (Afghanistan)", "پښتو (افغانستان)", },
    { 0x0029, "fa", "Persian", "فارسى", },
    { 0x0429, "fa_IR", "Persian", "فارسى (ايران)", },
    { 0x0015, "pl", "Polish", "polski", },
    { 0x0415, "pl_PL", "Polish (Poland)", "polski (Polska)", },
    { 0x0016, "pt", "Portuguese", "Português", },
    { 0x0416, "pt_BR", "Portuguese (Brazil)", "Português (Brasil)", },
    { 0x0816, "pt_PT", "Portuguese (Portugal)", "português (Portugal)", },
    { 0x0046, "pa", "Punjabi", "ਪੰਜਾਬੀ", },
    { 0x0446, "pa_IN", "Punjabi (India)", "ਪੰਜਾਬੀ (ਭਾਰਤ)", },
    { 0x046B, "quz_BO", "Quechua (Bolivia)", "runasimi (Bolivia Suyu)", },
    { 0x086B, "quz_EC", "Quechua (Ecuador)", "runasimi (Ecuador Suyu)", },
    { 0x0C6B, "quz_PE", "Quechua (Peru)", "runasimi (Peru Suyu)", },
    { 0x0018, "ro", "Romanian", "română", },
    { 0x0418, "ro_RO", "Romanian (Romania)", "română (România)", },
    { 0x0417, "rm_CH", "Romansh (Switzerland)", "Rumantsch (Svizra)", },
    { 0x0019, "ru", "Russian", "русский", },
    { 0x0419, "ru_RU", "Russian (Russia)", "русский (Россия)", },
    { 0x243B, "smn_FI", "Sami, Inari (Finland)", "sämikielâ (Suomâ)", },
    { 0x103B, "smj_NO", "Sami, Lule (Norway)", "julevusámegiella (Vuodna)", },
    { 0x143B, "smj_SE", "Sami, Lule (Sweden)", "julevusámegiella (Svierik)", },
    { 0x0C3B, "se_FI", "Sami, Northern (Finland)", "davvisámegiella (Suopma)", },
    { 0x043B, "se_NO", "Sami, Northern (Norway)", "davvisámegiella (Norga)", },
    { 0x083B, "se_SE", "Sami, Northern (Sweden)", "davvisámegiella (Ruoŧŧa)", },
    { 0x203B, "sms_FI", "Sami, Skolt (Finland)", "sääm´ǩiõll (Lää´ddjânnam)", },
    { 0x183B, "sma_NO", "Sami, Southern (Norway)", "åarjelsaemiengiele (Nöörje)", },
    { 0x1C3B, "sma_SE", "Sami, Southern (Sweden)", "åarjelsaemiengiele (Sveerje)", },
    { 0x004F, "sa", "Sanskrit", "संस्कृत", },
    { 0x044F, "sa_IN", "Sanskrit (India)", "संस्कृत (भारतम्)", },
    { 0x7C1A, "sr", "Serbian", "srpski", },
    { 0x1C1A, "sr_Cyrl_BA", "Serbian (Cyrillic, Bosnia and Herzegovina)", "српски (Босна и Херцеговина)", },
    { 0x0C1A, "sr_Cyrl_SP", "Serbian (Cyrillic, Serbia)", "српски (Србија и Црна Гора)", },
    { 0x181A, "sr_Latn_BA", "Serbian (Latin, Bosnia and Herzegovina)", "srpski (Bosna i Hercegovina)", },
    { 0x081A, "sr_Latn_SP", "Serbian (Latin, Serbia)", "srpski (Srbija i Crna Gora)", },
    { 0x046C, "nso_ZA", "Sesotho sa Leboa (South Africa)", "Sesotho sa Leboa (Afrika Borwa)", },
    { 0x0432, "tn_ZA", "Setswana (South Africa)", "Setswana (Aforika Borwa)", },
    { 0x045B, "si_LK", "Sinhala (Sri Lanka)", "සිංහ (ශ්‍රී ලංකා)", },
    { 0x001B, "sk", "Slovak", "slovenčina", },
    { 0x041B, "sk_SK", "Slovak (Slovakia)", "slovenčina (Slovenská republika)", },
    { 0x0024, "sl", "Slovenian", "slovenski", },
    { 0x0424, "sl_SI", "Slovenian (Slovenia)", "slovenski (Slovenija)", },
    { 0x000A, "es", "Spanish", "español", },
    { 0x2C0A, "es_AR", "Spanish (Argentina)", "Español (Argentina)", },
    { 0x400A, "es_BO", "Spanish (Bolivia)", "Español (Bolivia)", },
    { 0x340A, "es_CL", "Spanish (Chile)", "Español (Chile)", },
    { 0x240A, "es_CO", "Spanish (Colombia)", "Español (Colombia)", },
    { 0x140A, "es_CR", "Spanish (Costa Rica)", "Español (Costa Rica)", },
    { 0x1C0A, "es_DO", "Spanish (Dominican Republic)", "Español (República Dominicana)", },
    { 0x300A, "es_EC", "Spanish (Ecuador)", "Español (Ecuador)", },
    { 0x440A, "es_SV", "Spanish (El Salvador)", "Español (El Salvador)", },
    { 0x100A, "es_GT", "Spanish (Guatemala)", "Español (Guatemala)", },
    { 0x480A, "es_HN", "Spanish (Honduras)", "Español (Honduras)", },
    { 0x080A, "es_MX", "Spanish (Mexico)", "Español (México)", },
    { 0x4C0A, "es_NI", "Spanish (Nicaragua)", "Español (Nicaragua)", },
    { 0x180A, "es_PA", "Spanish (Panama)", "Español (Panamá)", },
    { 0x3C0A, "es_PY", "Spanish (Paraguay)", "Español (Paraguay)", },
    { 0x280A, "es_PE", "Spanish (Peru)", "Español (Perú)", },
    { 0x500A, "es_PR", "Spanish (Puerto Rico)", "Español (Puerto Rico)", },
    { 0x0C0A, "es_ES", "Spanish (Spain)", "español (España)", },
    { 0x540A, "es_US", "Spanish (United States)", "Español (Estados Unidos)", },
    { 0x380A, "es_UY", "Spanish (Uruguay)", "Español (Uruguay)", },
    { 0x200A, "es_VE", "Spanish (Venezuela)", "Español (Republica Bolivariana de Venezuela)", },
    { 0x001D, "sv", "Swedish", "svenska", },
    { 0x081D, "sv_FI", "Swedish (Finland)", "svenska (Finland)", },
    { 0x041D, "sv_SE", "Swedish (Sweden)", "svenska (Sverige)", },
    { 0x005A, "syr", "Syriac", "ܣܘܪܝܝܐ", },
    { 0x045A, "syr_SY", "Syriac (Syria)", "ܣܘܪܝܝܐ (سوريا)", },
    { 0x0428, "tg_Cyrl_TJ", "Tajik (Cyrillic, Tajikistan)", "Тоҷикӣ (Тоҷикистон)", },
    { 0x085F, "tzm_Latn_DZ", "Tamazight (Latin, Algeria)", "Tamazight (Djazaïr)", },
    { 0x0049, "ta", "Tamil", "தமிழ்", },
    { 0x0449, "ta_IN", "Tamil (India)", "தமிழ் (இந்தியா)", },
    { 0x0044, "tt", "Tatar", "Татар", },
    { 0x0444, "tt_RU", "Tatar (Russia)", "Татар (Россия)", },
    { 0x004A, "te", "Telugu", "తెలుగు", },
    { 0x044A, "te_IN", "Telugu (India)", "తెలుగు (భారత దేశం)", },
    { 0x001E, "th", "Thai", "ไทย", },
    { 0x041E, "th_TH", "Thai (Thailand)", "ไทย (ไทย)", },
    { 0x0451, "bo_CN", "Tibetan (PRC)", "བོད་ཡིག (ཀྲུང་ཧྭ་མི་དམངས་སྤྱི་མཐུན་རྒྱལ་ཁབ།)", },
    { 0x001F, "tr", "Turkish", "Türkçe", },
    { 0x041F, "tr_TR", "Turkish (Turkey)", "Türkçe (Türkiye)", },
    { 0x0442, "tk_TM", "Turkmen (Turkmenistan)", "türkmençe (Türkmenistan)", },
    { 0x0480, "ug_CN", "Uighur (PRC)", "ئۇيغۇر يېزىقى (جۇڭخۇا خەلق جۇمھۇرىيىتى)", },
    { 0x0022, "uk", "Ukrainian", "україньска", },
    { 0x0422, "uk_UA", "Ukrainian (Ukraine)", "україньска (Україна)", },
    { 0x042E, "wen_DE", "Upper Sorbian (Germany)", "hornjoserbšćina (Němska)", },
    { 0x0020, "ur", "Urdu", "اُردو", },
    { 0x0420, "ur_PK", "Urdu (Islamic Republic of Pakistan)", "اُردو (پاکستان)", },
    { 0x0043, "uz", "Uzbek", "U'zbek", },
    { 0x0843, "uz_Cyrl_UZ", "Uzbek (Cyrillic, Uzbekistan)", "Ўзбек (Ўзбекистон)", },
    { 0x0443, "uz_Latn_UZ", "Uzbek (Latin, Uzbekistan)", "U'zbek (U'zbekiston Respublikasi)", },
    { 0x002A, "vi", "Vietnamese", "Tiếng Việt", },
    { 0x042A, "vi_VN", "Vietnamese (Vietnam)", "Tiếng Việt (Việt Nam)", },
    { 0x0452, "cy_GB", "Welsh (United Kingdom)", "Cymraeg (y Deyrnas Unedig)", },
    { 0x0488, "wo_SN", "Wolof (Senegal)", "Wolof (Sénégal)", },
    { 0x0485, "sah_RU", "Yakut (Russia)", "саха (Россия)", },
    { 0x0478, "ii_CN", "Yi (PRC)", "ꆈꌠꁱꂷ (ꍏꉸꏓꂱꇭꉼꇩ)", },
    { 0x046A, "yo_NG", "Yoruba (Nigeria)", "Yoruba (Nigeria)", },

# if 0
    { -1, "de_BE", "German (Belgium)", "Deutsch (Belgien)", },
    { -1, "nl_AW", "Dutch (Aruba)", "Nederlands (Aruba)", },
    { -1, "nl_SR", "Dutch (Surinam)", "Nederlands (Suriname)", },
    { -1, "nl_AN", "Dutch (Antilles)", "Nederlands (Antillen)", },
# endif
};

const int TEXT_LcIdCount= sizeof(TEXT_LcIds)/sizeof(MsLcid);
