/* confdefs.h */
#define PACKAGE_NAME ""
#define PACKAGE_TARNAME ""
#define PACKAGE_VERSION ""
#define PACKAGE_STRING ""
#define PACKAGE_BUGREPORT ""
#define PACKAGE_URL ""
#define HAVE_LIBXPM 1
#define USE_LIBXPM 1
#define HAVE_FT2 1
#define HAVE_FONTCONFIG 1
#define USE_FONTCONFIG 1
#define HAVE_XFT 1
#define USE_XFT 1
#define STDC_HEADERS 1
#define HAVE_GTK 1
#define USE_GTK 1
#define HAVE_MOTIF 1
#define USE_MOTIF 1
#define USE_GTK 1 
#define USE_MOTIF 0 
#define USE_HEADLESS 0 
